### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by oyvindsk**
Made a Dockerfile to create a docker image to build this book without having to install all the dependencies "locally".

Include it if you want :)

### CODE REVIEW

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[gobook] Added Dockerfile (#50)..." ]
>Made a Dockerfile to create a docker image to build this book without having to install all the dependencies "locally".
>
>Include it if you want :)
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/miekg/gobook/pull/50
>
>-- Commit Summary --
>
>  * Added Dockerfile
>
>-- File Changes --
>
>    A Dockerfile/Dockerfile (41)
>    A Dockerfile/Readme.md (25)
>    A Dockerfile/get-and-build.sh (28)
>
>-- Patch Links --
>
>https://github.com/miekg/gobook/pull/50.patch
>https://github.com/miekg/gobook/pull/50.diff

I might have something better: http://miek.nl/go/

**Comment by oyvindsk** [comment]
That's pretty cool! PDF's are still useful though..

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [gobook] Added Dockerfile (#50)..." ]
>That's pretty cool! PDF's are still useful though..

yep, that why this should/could be translated back to LaTeX again and be
printed. (I "only" need to write the LaTeX output plugin for this)

**Comment by oyvindsk** [comment]
yikes, that does not sound like fun :)

**Pull request closed without merging**
